### ISSUE TITLE
As a Devops, I would like to have a consistent handling of environment variables

### ISSUE THREAD

**Issue by SonOfLope** [ai-cfia/github-workflows#80]
## Introduction
Our goal here is to streamline and standardize the way we handle environment variables across our deployment workflows. This involves a unified approach to managing secrets and environment variables, whether they are used in Kubernetes or in our GitHub Actions workflows.

## Issues
This epic encompasses several related issues, some of which are completed, but are included here for better tracking.

- [x] [Allow the Use of ENV File in Deployment Workflows](https://github.com/ai-cfia/github-workflows/issues/58)
- [x] [Manage Application Secrets Inside Kubernetes - Vault Integration](https://github.com/ai-cfia/infra/issues/19)
- [x] [As a developer, I want to manage my secrets that will be used inside our Github Action workflow and deployment](https://github.com/ai-cfia/infra/issues/24)

## Background
Our current approach to secret management, solely through GitHub secrets, poses limitations in scalability, security, and centralized control. The absence of a unified system leads to potential inconsistencies and security vulnerabilities. By moving towards HashiCorp Vault, we aim to create a more robust, secure, and scalable system for managing environment variables and secrets. This transition will not only enhance our security posture but also streamline our deployment processes, reducing manual effort and the risk of errors.

Significant enhancement in this transition will be the implementation of a structured review process for any changes made to secrets (Preventing cases like this [one](https://github.com/ai-cfia/dev-rel-docs/pull/99)). This means that updates, deletions, or additions of secrets will undergo a thorough review process, similar to code changes, to ensure accuracy and security.

---

This epic will be updated as we progress, with new issues being added or existing issues being updated based on our ongoing experience and feedback.

---

## Related Documents and Links
- [HashiCorp Vault Documentation](https://www.vaultproject.io/docs)
- [GitHub Actions Secrets Documentation](https://docs.github.com/en/actions/security-guides/encrypted-secrets)

---

**Comment by rngadam** [comment]
There's a lot of judgments being thrown around without references, objective facts or explanations as to why one solution is better than the other.

For our particular needs, isn't it more suitable for us to use External Secrets with Azure Keyvault?

https://external-secrets.io/latest/provider/azure-key-vault/

**Comment by ThomasCardin** [comment]
We could also use https://github.com/tellerops/teller instead of `external-secrets`

**Comment by ThomasCardin** [comment]
Note: For vault we can manage environment var with https://github.com/hashicorp/vault-action and use this 
![image](https://github.com/ai-cfia/github-workflows/assets/49320132/c32d71f2-6bfe-4980-9328-03805812eafb)

We can reserve the .json to export every key/value pair with `jq`

**Comment by SonOfLope** [comment]
this is done
